baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Telecom Data Platform"

[params]
  apiBaseUrl = "http://localhost:5000"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

